---
name: Michael Luu,
surname: MPH
position: "Research Biostatistician II"
address: "Samuel Oschin Comprehensive Cancer Institute"
www: michaelluu.info
email: "michael.luu@cshs.org"
github: mluu921
linkedin: mluu921
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "414141"
output: 
  vitae::awesomecv:
    page_total: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = T)
library(vitae)
library(tidyverse)
library(here)
library(RefManageR)
library(lubridate)
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "M.P.H. in Biostatistics & Epidemiology", "2015", "University of Southern California", "Los Angeles, California",
  "B.Sc. in Biological Sciences", "2009", "University of California, Irvine", "Irvine, California"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Profesional Experience

```{r}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Research Biostatistician II", "Samuel Oschin Comprehensive Cancer Institute", "Los Angeles, California", "2016 - Present", 
    list("Assist and collaborate in preparation of grant proposals, protocol designs, publications, and presentation by providing statistical support for sample size determination and power analysis.",
         "Analysis of large cancer registry for survival outcomes from the National Cancer Database (NCDB), and the Surveillance, Epidemiology, and End Results Program (SEER-Medicare) from the National Cancer Institute (NCI)"
    ),
  "Research Biostatistician I", "Children's Hospital Los Angeles", "Los Angeles, California", "2016", 
    list("Provided statistical support to a multidisciplinary group of faculty physicians, residents, and fellows in study design, power analysis, sample size calculation and data analysis."
    ),
  "Quality Improvement Analyst", "Children's Hospital Los Angeles", "Los Angeles, California", "2015 - 2016", 
    list("Collaborated with a multidisciplinary NICCU quality improvement team by providing key analytic insight and development of key analytical tools that directly affect patient care, such as the CHLA/USC Division of Neonatology Enteral Feeding Calculator, and CHLA/USC Division of Neonatology Hand Hygiene Dashboard."
    ),
  "Epidemiology & Outcomes Research Intern", "Children's Hospital Los Angeles", "Los Angeles, California", "2014 - 2015", 
    list("Performed exploratory analysis on large administrative databases such as the Healthcare Cost and Utilization Project Kids Inpatient Database (HCUP-KIDs), California’s Office of Statewide Health Planning and Development and Pediatrics Health Information Systems consisting of more than 100 thousand observations and explored the relationship of resource utilization and outcomes on the high risk neonatal population."
    )
) %>% 
  detailed_entries(role, dates, company, loc, details)
```

# Teaching Experience

```{r}
tribble(
  ~ class,  ~ place,  ~ dates,  ~ details, ~ where,
  'BMS510 - Biostatistics', 
  'Cedars-Sinai Cancer Center', '2018 - present', 'Co-instructor in the biostatistics course for the biomedical sciences PhD program. Taught the introductory portion to the R programming language, data manipulation with the suite of packages as well as data visualization using ggplot2',
  'Los Angles, California'
  
) %>%
  detailed_entries(., with = class, what = place , when = dates, where = where, why = details)

```

# Software Development
```{r}
tribble(
  ~ class,
  ~ place,
  ~ details,
  ~ where,
  'CHLA/USC Division of Neonatology Enteral Feeding Calculator',
  'https://nicu.shinyapps.io/feedingcalc',
  'A web based online interactive calculator built on top of the R Shiny framework. This web application implements the enteral feeding algorithm developed internally by the quality improvement team of neonatologist and nurses at CHLA by simplifying the necessity for manual calculation, and by providing an interactive environment for custom parameters and report generation. This web application has been implemented and is in currently in clinical use at Children’s Hospital Los Angeles, LAC/USC Medical Center, and Hollywood Presbyterian Medical Center.',
  NA
) %>%
  detailed_entries(., with = class, what = place, where = where, why = details)
```

# Graduate Coursework

```{r}
tribble(
  ~ details,
  'Health Service Delivery in the U.S.',
  'Principles of Epidemiology',
  'Principles of Biostatistics',
  'Foundation in Health Education and Promotion',
  'Environmental Health: An Epidemiological Approach',
  'Epidemiology of Infections Disease',
  'Data Analysis: Analysis of Continuous Data',
  'Genetics in Public Health and Preventive Medicine',
  'Biological Basis of Disease',
  'Data Analysis: Analysis of Categorical Data',
  'Public Health Leadership and Management'
) %>% detailed_entries(why = details)
```

# Professional Activities

```{r}
tribble(
  ~ details,
  'Attended the following professional conferences:',
  'The Pediatric Academic Societies Annual Meeting (2015), San Diego, CA',
  'The Pediatric Academic Societies Annual Meeting (2016), Baltimore, MD',
  'California Association of Neonatologists: Cool Topics in Neonatology (2016), San Diego, CA',
  'American Academy of Pediatrics (2015), Washington, D.C.',
  'Joint Statistical Meeting (2017), Baltimore, MD',
  'Join Statistical Meeting (2019), Denver, CO'
) %>% detailed_entries(why = details)
```


# Profesional Membership

```{r}

tribble(
  ~what, ~when, ~with, ~where, ~why,
  '', '','American Statistical Association', '2018 - present', ''
) %>%
  detailed_entries(., with = with, where = where)
```

\newpage 

```{r, results = 'asis'}
bib <- RefManageR::ReadPubMed('Michael Luu', retmax = 999)

for(i in 2017:year(Sys.Date())) {
  
  cat('\n\n')
  
  cat('# Peer Reviewed Publications')
  
  cat('\n\n')
  
  cat('# ', i, '\n\n')
  
  SearchBib(bib, year = as.character(i), author = 'Michael Luu', .opts = list(match.author = 'exact')) %>% print()
  
  cat('\\newpage')
  
  cat('\n\n')
  
} 

```



